Review; removing fastqc and fixing paths

diff --git a/.github/workflows/nf-test.yml b/.github/workflows/nf-test.yml
--- a/.github/workflows/nf-test.yml
+++ b/.github/workflows/nf-test.yml
@@ -1,4 +1,4 @@
-name: Run nf-test
+name: nf-test
 on:
   pull_request:
     paths-ignore:
@@ -61,7 +61,7 @@ jobs:
           - "latest-everything"
     env:
       NXF_ANSI_LOG: false
-      TOTAL_SHARDS: ${{ needs.find-tests.outputs.total_shards }}
+      TOTAL_SHARDS: ${{ needs.nf-test-changes.outputs.total_shards }}
 
     steps:
       - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
@@ -79,20 +79,20 @@ jobs:
           shard: 1
           total_shards: 1
 
-      # - name: Report test status
-      #   if: ${{ always() }}
-      #   run: |
-      #     if [[ "${{ steps.run_nf_test.outcome }}" == "failure" ]]; then
-      #       echo "::error::Test with ${{ matrix.NXF_VER }} failed"
-      #       # Add to workflow summary
-      #       echo "## ❌ Test failed: ${{ matrix.profile }} | ${{ matrix.NXF_VER }} | Shard ${{ matrix.shard }}/${{ env.TOTAL_SHARDS }}" >> $GITHUB_STEP_SUMMARY
-      #       if [[ "${{ matrix.NXF_VER }}" == "latest-everything" ]]; then
-      #         echo "::warning::Test with latest-everything failed but will not cause workflow failure. Please check if the error is expected or if it needs fixing."
-      #       fi
-      #       if [[ "${{ matrix.NXF_VER }}" != "latest-everything" ]]; then
-      #         exit 1
-      #       fi
-      #     fi
+      - name: Report test status
+        if: ${{ always() }}
+        run: |
+          if [[ "${{ steps.run_nf_test.outcome }}" == "failure" ]]; then
+            echo "::error::Test with ${{ matrix.NXF_VER }} failed"
+            # Add to workflow summary
+            echo "## ❌ Test failed: ${{ matrix.profile }} | ${{ matrix.NXF_VER }} | Shard ${{ matrix.shard }}/${{ env.TOTAL_SHARDS }}" >> $GITHUB_STEP_SUMMARY
+            if [[ "${{ matrix.NXF_VER }}" == "latest-everything" ]]; then
+              echo "::warning::Test with latest-everything failed but will not cause workflow failure. Please check if the error is expected or if it needs fixing."
+            fi
+            if [[ "${{ matrix.NXF_VER }}" != "latest-everything" ]]; then
+              exit 1
+            fi
+          fi
 
   confirm-pass:
     needs: [nf-test]
