edit nf-test 3

diff --git a/.github/workflows/nf-test.yml b/.github/workflows/nf-test.yml
--- a/.github/workflows/nf-test.yml
+++ b/.github/workflows/nf-test.yml
@@ -25,48 +25,31 @@ env:
   NXF_SINGULARITY_LIBRARYDIR: ${{ github.workspace }}/.singularity
 
 jobs:
-  nf-test-changes:
-    name: nf-test-changes
-    runs-on: 
-      - runs-on= ubuntu-latest  
+  find-tests:
+    runs-on: ubuntu-latest  
     outputs:
-      shard: ${{ steps.set-shards.outputs.shard }}
-      total_shards: ${{ steps.set-shards.outputs.total_shards }}
+      tags: ${{ steps.find.outputs.tags }}
     steps:
-      - name: Clean Workspace # Purge the workspace in case it's running on a self-hosted runner
-        run: |
-          ls -la ./
-          rm -rf ./* || true
-          rm -rf ./.??* || true
-          ls -la ./
-      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
-        with:
-          fetch-depth: 0
+      - uses: actions/checkout@v4
 
-      - name: get number of shards
-        id: set-shards
-        uses: ./.github/actions/get-shards
-        env:
-          NFT_VER: ${{ env.NFT_VER }}
-        with:
-          max_shards: 7
+      - name: get subworkflows
+        id: find
+        uses: ./.github/actions/find-tests
 
       - name: debug
         run: |
-          echo ${{ steps.set-shards.outputs.shard }}
-          echo ${{ steps.set-shards.outputs.total_shards }}
+          echo ${{ steps.find.outputs.tags }}
 
   nf-test:
-    name: "${{ matrix.profile }} | ${{ matrix.NXF_VER }} | ${{ matrix.shard }}/${{ needs.nf-test-changes.outputs.total_shards }}"
-    needs: [nf-test-changes]
-    if: ${{ needs.nf-test-changes.outputs.total_shards != '0' }}
+    name: "${{ matrix.tag }} | ${{ matrix.profile }} | ${{ matrix.NXF_VER }}"
+    needs: [find-tests]
     runs-on: # use GitHub runners
       - "ubuntu-latest"
     strategy:
       fail-fast: false
       matrix:
-        shard: ${{ fromJson(needs.nf-test-changes.outputs.shard) }}
         profile: [docker, singularity]
+        tag: ${{ fromJson(needs.find-tests.outputs.tags) }}
         isMain:
           - ${{ github.base_ref == 'master' || github.base_ref == 'main' }}
         # Exclude conda and singularity on dev
@@ -78,7 +61,7 @@ jobs:
           - "latest-everything"
     env:
       NXF_ANSI_LOG: false
-      TOTAL_SHARDS: ${{ needs.nf-test-changes.outputs.total_shards }}
+      TOTAL_SHARDS: ${{ needs.find-tests.outputs.total_shards }}
 
     steps:
       - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
@@ -86,31 +69,30 @@ jobs:
           fetch-depth: 0
 
       - name: Run nf-test
-        id: run_nf_test
+        if: matrix.profile != ''
         uses: ./.github/actions/nf-test
         continue-on-error: ${{ matrix.NXF_VER == 'latest-everything' }}
         env:
           NFT_WORKDIR: ${{ env.NFT_WORKDIR }}
-          NXF_VERSION: ${{ matrix.NXF_VER }}
         with:
           profile: ${{ matrix.profile }}
-          shard: ${{ matrix.shard }}
-          total_shards: ${{ env.TOTAL_SHARDS }}
+          shard: 1
+          total_shards: 1
 
-      - name: Report test status
-        if: ${{ always() }}
-        run: |
-          if [[ "${{ steps.run_nf_test.outcome }}" == "failure" ]]; then
-            echo "::error::Test with ${{ matrix.NXF_VER }} failed"
-            # Add to workflow summary
-            echo "## ❌ Test failed: ${{ matrix.profile }} | ${{ matrix.NXF_VER }} | Shard ${{ matrix.shard }}/${{ env.TOTAL_SHARDS }}" >> $GITHUB_STEP_SUMMARY
-            if [[ "${{ matrix.NXF_VER }}" == "latest-everything" ]]; then
-              echo "::warning::Test with latest-everything failed but will not cause workflow failure. Please check if the error is expected or if it needs fixing."
-            fi
-            if [[ "${{ matrix.NXF_VER }}" != "latest-everything" ]]; then
-              exit 1
-            fi
-          fi
+      # - name: Report test status
+      #   if: ${{ always() }}
+      #   run: |
+      #     if [[ "${{ steps.run_nf_test.outcome }}" == "failure" ]]; then
+      #       echo "::error::Test with ${{ matrix.NXF_VER }} failed"
+      #       # Add to workflow summary
+      #       echo "## ❌ Test failed: ${{ matrix.profile }} | ${{ matrix.NXF_VER }} | Shard ${{ matrix.shard }}/${{ env.TOTAL_SHARDS }}" >> $GITHUB_STEP_SUMMARY
+      #       if [[ "${{ matrix.NXF_VER }}" == "latest-everything" ]]; then
+      #         echo "::warning::Test with latest-everything failed but will not cause workflow failure. Please check if the error is expected or if it needs fixing."
+      #       fi
+      #       if [[ "${{ matrix.NXF_VER }}" != "latest-everything" ]]; then
+      #         exit 1
+      #       fi
+      #     fi
 
   confirm-pass:
     needs: [nf-test]
